# The Search for the NumPyte Crystal

You've finally reached it, the cave of the NumPyte Crystal! After many grueling weeks of training, packing, and climbing, you've arrived at the mouth of Array Cave in the mountains of Datalore - and it's exactly what it looks like in the pictures. Better, even! But now the journey has only just begun, as the reason you're here - the same reason as everyone else who makes the journey to the cave's entrance - is to solve the Mystery of Matrix Grotto and acquire the NumPyte crystal deep within the caverns of the mountain. Be sure that you're prepared - you'll need the toolkit the masters built for you to aid you in this mission. You also have your [guidebook](https://numpy.org/doc/stable/user/absolute_beginners#), a common resource for all adventurers to this particular cave. With these two resources at your disposal, this adventure should be an absolute breeze.

## Preparing Your Toolkit

Before you venture further into Array Cave, you'll need to make sure everything's prepped and ready to go; nobody wants to be stuck in a cave without the proper equipment!

In [4]:
# Check for NumPy - you rummage in your pack for your trusty toolkit
try:
    import numpy as np
except ImportError:
    raise ImportError("You can't proceed into the cave without NumPy!")

In [2]:
# Uncomment and run the line below if you got an ImportError in the cell above
# !pip install numpy

After a quick snack break and equipment check, you're ready to begin your descent.

## The Creatrium

As you enter the cave, the air stills and grows slightly warmer. The mouth of the cave narrows to a small tunnel curving downwards in a spiral.

According to your map, just below the mouth of the cave is a small chamber that collects the meltwater from the peak above and distills it into a spring. This spring feeds caverns below it and nourishes a beautiful ecosystem of plants, fungi, and animals. The cavern is known to explorers as the Creatrium.

You arrive at the bottom of the spiral tunnel and the Creatrium greets you with what sounds like a brook, its babbles distorted by the cave walls. The spring is in an alcove built into the side of the small room, with a stream of pure water trickling over the rim, onto the floor, and down a small passageway. You can hear it echoing further into the mountain.

You understand that this water is of the purest snow from the highest peak in Datalore - its properties are powerful and beneficial. You know from your research that although the water flows below, it doesn't remain as pure, so you'll want to store some for later. Your toolkit is designed specifically for this purpose: you can use it to create and manipulate vials that will store different liquids that you find on your adventures. [This page](https://numpy.org/doc/stable/user/absolute_beginners#how-to-create-a-basic-array) in your guidebook should help with making particular types of arrays that your vials can store.

### Task 1: Making a Sourcewater Vial

In [67]:
sw_vial = None

# Reassign sw_vial to a NumPy array of 10 zeros
### BEGIN SOLUTION
sw_vial=np.zeros(10)
### END SOLUTION

print(sw_vial)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
assert sw_vial is not None, "sw_vial must be assigned to something!"
### BEGIN HIDDEN TESTS
assert isinstance(sw_vial, np.ndarray), "sw_vial must be a NumPy array!"
assert sw_vial.shape == (10,), "sw_vial must be a 1D array of length 10!"
assert np.all(sw_vial == 0), "sw_vial must be an array of zeros!"
### END HIDDEN TESTS
print("Success!")

Success!


### Task 2: Adjusting the Vial Size

You hear a voice, unable to discern from where it came. "Take only what you need...and you need a little more", it says. A small ampoule forms in the pool of water. You feel an urge to [`.concatenate()`](https://numpy.org/doc/stable/user/absolute_beginners.html#adding-removing-and-sorting-elements) this ampoule onto your own vial.


In [69]:
sw_ampoule = np.zeros(6)
print(f"The size of sw_ampoule is: {sw_ampoule.size}")
print(f"The size of sw_vial is: {sw_vial.size}")

# Concatenate sw_ampoule onto sw_vial and delete sw_vial
### BEGIN SOLUTION
sw_vial= np.concatenate((sw_vial,sw_ampoule),axis=0)
del sw_ampoule
### END SOLUTION

print("The size of sw_vial is now:", sw_vial.size)

The size of sw_ampoule is: 6
The size of sw_vial is: 10
The size of sw_vial is now: 16


In [74]:
assert isinstance(sw_vial, np.ndarray), "sw_vial must be a NumPy array!"
### BEGIN HIDDEN TESTS
assert sw_vial.shape == (16,), "sw_vial must be a 1D array of length 16!"
assert np.all(sw_vial == 0), "sw_vial must be an array of zeros!"
assert "sw_ampoule" not in locals(), "sw_ampoule must be deleted!"
### END HIDDEN TESTS
print("Success!")

AssertionError: sw_vial must be a 1D array of length 16!

### Task 3: Adjusting the Vial Shape

The vial is now a bit larger than you originally intended, but if it's what the headless voice wants, then it must be so. You feel it would be best to [`.reshape()`](https://numpy.org/doc/stable/user/absolute_beginners.html#can-you-reshape-an-array) it a bit to make it a little easier to carry. However, even though you can see it with perfect clarity, you can't distinguish its shape with any particular certainty. Luckily, your toolkit comes in handy for measuring and manipulating not just the size of an array, but its [shape](https://numpy.org/doc/stable/user/absolute_beginners.html#how-do-you-know-the-shape-and-size-of-an-array)!

In [71]:
print(f"The shape of sw_vial is: {sw_vial.shape}.")
# Reshape sw_vial to have a shape of (8, 2)
### BEGIN SOLUTION
sw_vial = np.reshape(sw_vial, (8,2))
### END SOLUTION

print(f"Now the shape of sw_vial is: {sw_vial.shape}.")
sw_vial

The shape of sw_vial is: (16,).
Now the shape of sw_vial is: (8, 2).


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [72]:
assert isinstance(sw_vial, np.ndarray), "sw_vial must be a NumPy array!"
### BEGIN HIDDEN TESTS
assert sw_vial.shape == (8, 2), "sw_vial must be a 2D array of shape (8, 2)!"
assert np.all(sw_vial == 0), "sw_vial must be an array of zeros!"
### END HIDDEN TESTS
print("Success!")

Success!


You now have a vial that's twice as stout as it once was and able to fit in your pocket. This is where you promptly store it and continue through the passageway, further downwards.

## The Prophecy


You follow the stream of Sourcewater and your descent brings you to the edge of a glowing orange chasm. The glow seems to be originating from the bottom of the chasm, and rising up with small reddish blobs of gel. You know you'll need another vial of this substance, which you recognize as Firejelly. However, your eyes are drawn to the letters on the wall of the chasm. In wide, cracked gouges - as if a giant had scrawled upon it - the wall reads:

"The purest fire and the purest water, when combined in the right way, is the lifeblood of the Great Hero of the New Age. This solution, distilled into a single drop and applied to the Great Hero's vessel, combined with the Hero's true name spoken aloud, is enough to rouse them from their sleep. Only then will the Hero reveal the NumPyte Crystal."

You spot a small bridge leading across the chasm. On the other side you see an archway, indicating the resuming passageway leads onward. You pull out your notes and find the pages that show the recipe for the solution. It reads: 

"Firejelly and Sourcewater react quite violently when they come into contact with each other. However, with the right shape and size, these two fluids can be combined to create Witskey, an extremely potent revival potion. You will need to weave these two liquids together when the time is right."

That seems pretty straight-forward - you just have to GET some firejelly.

### Task 4: Extract Some Firejelly Without Falling

As you step onto the bridge, you notice that it is PRECARIOUS. Each step is a chance that you may fall. There are cracks in EVERY plank, and you need to use your toolkit to find the planks where you can harvest some Firejelly. You scan the bridge for the strength of each plank.

In [76]:
# This is the bridge - planks that you can safely stop on have a sum greater than 10
BRIDGE = np.array([
    [2, 5],
    [4, 5],
    [6, 2],
    [3, 7],
    [1, 3],
    [5, 2],
    [2, 5],
    [4, 5],
    [6, 8],
    [3, 7],
    [1, 3],
    [5, 6]
])

You know that your toolkit has methods to analyze each cell in an array for a certain condition. You'll need to sum each plank and determine where the planks are strong enough (greater than 10) for you to grab some Firejelly. Some suggestions from the guidebook:
- [indexing](https://numpy.org/doc/stable/user/absolute_beginners#indexing-and-slicing)
- [`.where()`](https://numpy.org/doc/stable/reference/generated/numpy.where.html)
- [`.sum()`](https://numpy.org/doc/stable/user/absolute_beginners#basic-array-operations)

In [89]:
# Find the indices in the bridge where the sum of the two items in each row is greater than 10.
# bridge_indices should return a 1-D array.
bridge_indices = None
### BEGIN SOLUTION
bridge_indices = np.where(BRIDGE.sum(axis=1) > 10)[0]
### END SOLUTION

bridge_indices

array([ 8, 11])

In [90]:
assert bridge_indices is not None, "bridge_indices must be assigned to something!"
### BEGIN HIDDEN TESTS
assert isinstance(bridge_indices, np.ndarray), "bridge_indices must be a NumPy array!"
assert bridge_indices.shape == (2,), "bridge_indices must be a 1D array of length 2!"
### END HIDDEN TESTS
print("Success!")

Success!


In [91]:
fj_vial = np.ones((sw_vial.shape[0], bridge_indices.shape[0]))

fj_vial

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

You make it to the other edge of the chasm, trying hard not to look down, and approach the exit. Now that you're closer to the archway, you can smell what seems to be soil and pine after a hard rain, and you can hear an odd intermittent beeping. There's a pattern to it, and after a few moments of listening you recognize it as Morse code. Luckily, you have a Morse datachip that you can use to create a translator with your toolkit, and a small recorder to convert the code to a text-based sequence of 'dits' ('.') and 'dahs' ('-'). Your current goal is to use the dictionary and these recorded dits and dahs to reveal the nature of the Morse call.

### Task 5: Translate the Morse

In [92]:
morse = {
       '.-': 'A',
       '-...': 'B',
       '-.-.': 'C',
       '-..': 'D',
       '.': 'E',
       '..-.': 'F',
       '--.': 'G',
       '....': 'H',
       '..': 'I',
       '.---': 'J',
       '-.-': 'K',
       '.-..': 'L',
       '--': 'M',
       '-.': 'N',
       '---': 'O',
       '.--.': 'P',
       '--.-': 'Q',
       '.-.': 'R',
       '...': 'S',
       '-': 'T',
       '..-': 'U',
       '...-': 'V',
       '.--': 'W',
       '-..-': 'X',
       '-.--': 'Y',
       '--..': 'Z',
       '.----': '1',
       '..---': '2',
       '...--': '3',
       '....-': '4',
       '.....': '5',
       '-....': '6',
       '--...': '7',
       '---..': '8',
       '----.': '9',
       '-----': '0',
       '--..--': ', ',
       '.-.-.-': '.',
       '..--..': '?',
       '-..-.': '/',
       '-....-': '-',
       '-.--.': '(',
       '-.--.-': ')'
}

signal = np.array(['.--', '....', '---', '.-..', '..', '...-', '.', '...', '..', '-.',
       '.-', '.--.', '..', '-.', '.', '.-', '.--.', '.--.', '.-..', '.',
       '..-', '-.', '-..', '.', '.-.', '-', '....', '.', '...', '.', '.-',
       '..--..'])

In [97]:
# Translate the ENCRYPTED_SIGNAL using the morse dictionary and a list comprehension
translated_signal = None
### BEGIN SOLUTION
translated_signal = ([morse.get(code, '?') for code in signal])
### END SOLUTION

print(translated_signal)

['W', 'H', 'O', 'L', 'I', 'V', 'E', 'S', 'I', 'N', 'A', 'P', 'I', 'N', 'E', 'A', 'P', 'P', 'L', 'E', 'U', 'N', 'D', 'E', 'R', 'T', 'H', 'E', 'S', 'E', 'A', '?']


In [98]:
assert translated_signal is not None, "translated_signal must be assigned to something!"
### BEGIN HIDDEN TESTS
assert isinstance(translated_signal, list), "translated_signal must be a list!"
assert len(translated_signal) == len(signal), "translated_signal must be the same length as signal!"
### END HIDDEN TESTS

Assign the signal's response (in English, not Morse) to a variable called 'signal_response'. We'll use this later.

In [99]:
signal_response = None
### BEGIN SOLUTION
signal_response = 'SPONGEBOB SQUAREPANTS'
### END SOLUTION

signal_response

'SPONGEBOB SQUAREPANTS'

### Task 6: Mix the Vials

You now have both vials and an odd question (to which you may already know the answer - if you don't, even down here, you have enough signal to browse the internet). Before moving on, you pull out a peculiar cross-hatched flask from your toolkit, one that's meant specifically to combine these two materials into one fluid. With a simple command, you can interleave the two vials into a single flask. You can use [`.dstack()`](https://numpy.org/doc/stable/reference/generated/numpy.dstack.html) and one of the methods you've used [above](#Task-3:-Adjusting-the-Vial-Shape) to stack the arrays depth-wise into a shape of (8, 4).

In [101]:
solution_flask = None

### BEGIN SOLUTION
mix_vial = np.dstack((sw_vial, fj_vial))
solution_flask = np.reshape(mix_vial,(8,4))
### END SOLUTION

solution_flask

array([[0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.]])

In [102]:
assert solution_flask is not None, "solution_flask must be assigned to something!"
### BEGIN HIDDEN TESTS
assert isinstance(solution_flask, np.ndarray), "solution_flask must be a NumPy array!"
assert solution_flask.shape == (8, 4), "solution_flask must be a 2D array of shape (8, 4)!"
assert np.isnan(solution_flask).any() == False, "solution_flask should not contain any NaN values!"
assert np.isinf(solution_flask).any() == False, "solution_flask should not contain any infinite values!"
assert (solution_flask >= 0).all(), "solution_flask should not contain any negative values!"
### END HIDDEN TESTS
print("Success!")


Success!


Well done, you've safely combined the Sourcewater and Firejelly to create Witskey! Now all that's left is to take it to the final chamber, where the vessel of the True Hero slumbers and the NumPyte shard awaits your discovery. With a deep breath, you pass through the final archway and step down the passageway to the Matrix Grotto.

## The Solution

You arrive in the final chamber, a marvelous living cathedral. Below, the Sourcewater from above drips into pools that mingle noisily with nearby Firejelly, create small sparking fireworks. Surrounding these pools are lush oases of shrubs, ferns, and wildflowers, thriving in the underground paradise. At the center of the vast cavern lies an overgrown temple, obviously left to ruin millennia ago. You climb down to the ruin and peak through the door. Inside, the pops and drips are muffled by the stone walls but you look through the torn rafters above and can see the stalactites on the ceiling, shimmering with Sourcewater and reflecting the orange of the Firejelly below. You step into the quiet room of the temple, and spot an oddly colored rectangle on a stone dais. It... seemed like a sponge, like one you would use for cleaning your sink. You feel a pull towards the dais from the flask at your hip. 

There is one final step - distilling the Witskey down to a single drop. There is nothing completely new to this step besides [broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting) to the values of the flask's array - a very useful trick even outside of this cave, as are all of the NumPy toolkit's many applications. You brace yourself and get to work.

### Task 7: Distill and Apply the Solution

In [108]:
# Distill the solution flask by: 
# - slicing the first 6 rows of solution_flask to distilled_solution,
# - multiplying these rows by 2 (broadcasting),
# - and finding the sum of the entire matrix.

distilled_solution = None
### BEGIN SOLUTION
s_slice = solution_flask[:6]
m_slice = s_slice*2
sum_slice = np.sum(m_slice)
distilled_solution = sum_slice
### END SOLUTION

distilled_solution

np.float64(24.0)

In [109]:
assert distilled_solution is not None, "distilled_solution must be assigned to something!"
### BEGIN HIDDEN TESTS
assert isinstance(distilled_solution, np.float64), "distilled_solution must be a NumPy float64!"
assert int(distilled_solution) == 24, "distilled_solution must be equal to the answer!"
print(f"""
Success!
You've distilled the Witskey to its purest form and drop it onto the golden sponge.
You hear a rumbling in the distance, and the cave begins to shake.
The sponge begins to glow, and you feel a rush of energy as you absorb the solution.
You hear a voice in your head, as if just waking from a deep, deep slumber.
'Who... who am I?'
You shout at the top of your lungs, 
      '{signal_response}'!
The cave shakes even more violently, and you hear a loud crash.
Looking up, you see the ceiling above you beginning to crumble.
There is no exit, and you are trapped. It seems as if all is lost.
You cover your head and accept that all is lost. Then, you hear,
    'I am... I am... {signal_response}! AND I AM READY!'
You are swept up by powerful hands and carried out of the cave, through the falling debris.
You emerge from the cave, and the hands set you down on the ground.
You look up to see a giant yellow sponge with a square face.
'You have freed me from my slumber, and I am eternally grateful.
I will grant you one wish, anything you desire.'
You think for a moment, and then you say,
'The NumPyte Shard! Is it destroyed?' The cave is rubble, and you fear the worst.
The sponge looks at you, and then looks down at the ground.
'The NumPyte Shard can never be destroyed...
So long as it lives on in the hearts of adventurers like you.'
And with that, the great sponge ascends into the sky, and you are left alone.
You glance down at the ground, and see a small crystal shaped like a simple, perfect hamburger.
You pick it up and feel a surge of energy, and you know that you possess the ~NumPyte Shard~.
With your toolkit and newfound power in hand, you set off on your next adventure in the land of Datalore.
""")
### END HIDDEN TESTS


Success!
You've distilled the Witskey to its purest form and drop it onto the golden sponge.
You hear a rumbling in the distance, and the cave begins to shake.
The sponge begins to glow, and you feel a rush of energy as you absorb the solution.
You hear a voice in your head, as if just waking from a deep, deep slumber.
'Who... who am I?'
You shout at the top of your lungs, 
      'SPONGEBOB SQUAREPANTS'!
The cave shakes even more violently, and you hear a loud crash.
Looking up, you see the ceiling above you beginning to crumble.
There is no exit, and you are trapped. It seems as if all is lost.
You cover your head and accept that all is lost. Then, you hear,
    'I am... I am... SPONGEBOB SQUAREPANTS! AND I AM READY!'
You are swept up by powerful hands and carried out of the cave, through the falling debris.
You emerge from the cave, and the hands set you down on the ground.
You look up to see a giant yellow sponge with a square face.
'You have freed me from my slumber, and I am eter

Congrats, you've finished the notebook! Want to know what happens? Submit to JupyterHub and your instructor will let you know when your feedback has been released - you'll be able to read the final paragraph of the adventure at that time!